#!/bin/bash

# JECRC No Dues System - Project Cleanup
# This script removes all redundant documentation and SQL files

echo "🧹 JECRC No Dues System - Project Cleanup"
echo "=========================================="
echo ""
echo "⚠️  WARNING: This will delete 42+ redundant files!"
echo ""
echo "Files to be deleted:"
echo "  - 20 redundant documentation files"
echo "  - 20+ redundant SQL scripts"
echo "  - 2 redundant test scripts"
echo "  - 2 sensitive files"
echo ""
read -p "❓ Are you sure you want to continue? (y/n): " -n 1 -r
echo ""
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "❌ Cleanup cancelled."
    exit 1
fi
echo ""

DELETED_COUNT=0

# Function to delete file safely
delete_file() {
    if [ -f "$1" ]; then
        rm "$1"
        echo "✅ Deleted: $1"
        ((DELETED_COUNT++))
    else
        echo "⚠️  Not found: $1"
    fi
}

echo "🗑️  Deleting redundant documentation files..."
echo "-------------------------------------------"
delete_file "ALL_ISSUES_FIXED.md"
delete_file "COMPLETE_FIX_GUIDE.md"
delete_file "COMPLETE_SETUP_GUIDE.md"
delete_file "COMPLETE_SETUP_WITH_STAFF_AND_EMAILS.md"
delete_file "DEPLOY_FIX_NOW.md"
delete_file "DEPLOY_NOW.bat"
delete_file "DEPLOY_NOW.sh"
delete_file "DEPLOYMENT_GUIDE.md"
delete_file "DEPLOYMENT_WARNINGS_EXPLAINED.md"
delete_file "FINAL_SOLUTION_SUMMARY.md"
delete_file "FIX_COLLEGE_EMAIL_ISSUE.md"
delete_file "FIX_EVERYTHING_COMPLETE_GUIDE.md"
delete_file "FIX_EVERYTHING_NOW.md"
delete_file "QUICK_START.md"
delete_file "README_HOSTING.md"
delete_file "STAFF_ACCOUNTS_SETUP_GUIDE.md"
delete_file "SYSTEM_STATUS_REPORT.md"
delete_file "VERCEL_ENV_SETUP.md"
delete_file "VISUAL_ENHANCEMENTS_GUIDE.md"
delete_file "COMPREHENSIVE_FIX_AND_DEPLOY.md"
delete_file "DEPLOY_FIXES_NOW.md"
echo ""

echo "🗑️  Deleting redundant SQL scripts..."
echo "------------------------------------"
delete_file "CHECK_AND_FIX_RLS.sql"
delete_file "COMPLETE_DATABASE_RESET_WITH_ALL_DATA.sql"
delete_file "COMPLETE_DATABASE_RESET.sql"
delete_file "FIX_MISSING_COLUMNS.sql"
delete_file "FIX_PRODUCTION_DATABASE.sql"
delete_file "scripts/add-manual-entry-flag.sql"
delete_file "scripts/add-manual-entry-system.sql"
delete_file "scripts/check-current-accounts-simple.sql"
delete_file "scripts/check-current-accounts.sql"
delete_file "scripts/create-accounts-from-csv.sql"
delete_file "scripts/create-all-staff-accounts.js"
delete_file "scripts/create-config-tables.sql"
delete_file "scripts/enable-realtime-replica-identity.sql"
delete_file "scripts/enable-realtime.sql"
delete_file "scripts/fix-college-email-domain.sql"
delete_file "scripts/fix-rls-policies.sql"
delete_file "scripts/FIXED_CONFIGURATION_SETUP.sql"
delete_file "scripts/ONE_CLICK_FIX_ALL_ISSUES.sql"
delete_file "scripts/optimize-realtime-triggers.sql"
delete_file "scripts/populate-config-tables.sql"
delete_file "scripts/setup-reapplication-system.sql"
delete_file "scripts/unify-notification-system.sql"
delete_file "scripts/update-department-emails.sql"
delete_file "scripts/update-department-notification-emails.sql"
delete_file "scripts/update-department-order.sql"
delete_file "scripts/update-manual-entries-table.sql"
delete_file "scripts/update-staff-role.sql"
delete_file "scripts/verify-and-fix-database.sql"
delete_file "scripts/verify-realtime-complete.sql"
delete_file "scripts/verify-realtime-setup.sql"
echo ""

echo "🗑️  Deleting redundant test scripts..."
echo "-------------------------------------"
delete_file "scripts/test-api-endpoint.js"
delete_file "scripts/test-complete-system.js"
echo ""

echo "🗑️  Deleting sensitive files..."
echo "------------------------------"
delete_file "ACCOUNT_CREDENTIALS.csv"
delete_file "jecrc-key.pem"
delete_file "scripts/deploy-to-aws.sh"
echo ""

echo "=========================================="
echo "✅ CLEANUP COMPLETE!"
echo "=========================================="
echo ""
echo "📊 Summary:"
echo "   - Files deleted: $DELETED_COUNT"
echo "   - Files kept:"
echo "     ✅ COMPLETE_ISSUES_AND_CLEANUP.md"
echo "     ✅ FINAL_COMPLETE_DATABASE_SETUP.sql"
echo "     ✅ scripts/check-database-status.js"
echo "     ✅ scripts/test-all-features.js"
echo "     ✅ scripts/create-admin-account.js"
echo "     ✅ scripts/create-default-admin.js"
echo "     ✅ scripts/create-specific-staff-accounts.js"
echo "     ✅ All source code (src/)"
echo ""
echo "💡 Next steps:"
echo "   1. Review changes: git status"
echo "   2. Commit cleanup: git add . && git commit -m 'Clean up redundant files'"
echo "   3. Deploy to production: bash DEPLOY_TO_PRODUCTION.sh"
echo ""